<?php $this->headScript()->appendFile('https://cdn.paddle.com/paddle/v2/paddle.js'); ?>
<?php $this->headMeta()->setName('robots', 'noindex,nofollow'); ?>
<?php $title = ___('Processing your Invoice'); ?>
<?php $this->setLayout('layout.phtml'); ?>
<?php $this->layoutNoMenu = true; ?>
<?php include $this->_script('_receipt.phtml'); ?>

<div class="checkout-container"></div>
<script>
    Paddle.Environment.set("<?php echo $environment; ?>"); // sandbox|production
    Paddle.Setup({
        token: "<?php echo $client_token; ?>", // replace with a client-side token
        // pwAuth: "<?php echo $retain_key; ?>", // replace with your Retain API key
        // pwCustomer: {email: "joe@example.com"}, // can pass the id or email of your logged-in customer
        checkout: {
            settings: {
                displayMode: "inline",
                theme: "light",
                locale: "en",
                frameTarget: "checkout-container",
                frameInitialHeight: "450",
                frameStyle: "width: 100%; min-width: 312px; background-color: transparent; border: none;",
                showAddTaxId: true,
                allowLogout: false,
                showAddDiscounts: false,
                successUrl: "https://paddle.com/thankyou",
            }
        },
        eventCallback: function(data) {
            switch(data.name) {
              case "checkout.loaded":
                console.log("Checkout opened");
                break;
              case "checkout.customer.created":
                console.log("Customer created");
                break;
              case "checkout.completed":
                console.log("Checkout completed");
                break;
              default:
                console.log(data);
            }
        }
    });
    Paddle.Checkout.open({
        transactionId: "<?php echo $txnid; ?>",
        successUrl: "https://paddle.com/thankyou",
        customData: null,
        customer: {
            email: "joe@example.com", // req
            address: {
              countryCode: "GB",   // req
              postalCode: "10021", // req
            },
            // business: {
            //   name: "ChatApp Inc.",
            //   taxIdentifier: "555952383"
            // }
        }
    });

    function calculateLocalConversion(data) {
        document.getElementById("paddle_conversion").style.display = "block";
        var first = data.eventData.checkout.prices.customer;
        document.getElementById("paddle_currency").innerHTML = first.currency;
        document.getElementById("paddle_total").innerHTML    = first.total+" "+first.currency;
        if (data.eventData.checkout.recurring_prices) {
            var second            = data.eventData.checkout.recurring_prices;
            var recurringCurrency = second.customer.currency;
            var recurringTotal    = second.customer.total;
            var intervalType      = second.interval.type;
            var intervalCount     = second.interval.length;
            var recurringString   = 'Then '+recurringTotal+" "+recurringCurrency+" / "+intervalType;
            if(intervalCount > 1) {
                recurringString = 'Then '+recurringTotal+" "+recurringCurrency+" / "+intervalCount+" "+intervalType+"s";
            }
            document.getElementById("paddle_terms").innerHTML = recurringString;
        }
    }
</script>
